# Generated by Django 5.1.6 on 2025-03-03 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
