# Generated by Django 5.1.6 on 2025-02-12 08:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_tag_article_commentaire_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'verbose_name': 'commentaire', 'verbose_name_plural': 'commentaires'},
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=tinymce.models.HTMLField(),
        ),
    ]
