# Generated by Django 5.1.6 on 2025-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_alter_article_slug_alter_commentaire_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='est_pulie',
            field=models.BooleanField(default=True),
        ),
    ]
