# Generated by Django 5.1.6 on 2025-02-16 19:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_alter_commentaire_options_alter_commentaire_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='texte',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
