# Generated by Django 5.1.6 on 2025-02-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_alter_article_texte_alter_commentaire_contenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='texte',
            new_name='contenu',
        ),
    ]
