# Generated by Django 5.1.6 on 2025-02-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_rename_texte_article_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_de_publication',
            field=models.DateField(auto_now=True),
        ),
    ]
