# Generated by Django 5.1.6 on 2025-02-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0008_about_team_vission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
    ]
