# Generated by Django 5.1.6 on 2025-02-22 01:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0009_remove_team_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='vission',
            name='contenu_mission',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='vission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mission'),
        ),
        migrations.AddField(
            model_name='vission',
            name='titre_mission',
            field=models.CharField(default='', max_length=255),
        ),
    ]
