# Generated by Django 5.1.6 on 2025-02-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0010_vission_contenu_mission_vission_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vission',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vission',
            name='contenu_mission',
            field=models.TextField(),
        ),
    ]
